---
- name: Create database
  mysql_db: name={{ onboard_db.name }} state=present config_file=/etc/mysql/debian.cnf
  register: db

- name: Initialize database
  mysql_db:
    state: import
    name: "{{ onboard_db.name }}"
    target: "{{ onboard_path }}/scripts/mysql.sql"
    config_file: /etc/mysql/debian.cnf
  when: db.changed

- name: Create database user
  mysql_user:
    name: "{{ onboard_db.username }}"
    password: "{{ onboard_db.password }}"
    priv: "{{ onboard_db.name }}.*:ALL"
    state: present
    config_file: /etc/mysql/debian.cnf

- name: Generate createAdminUser script
  template: src=createAdminUser.php dest={{ onboard_path }}/scripts/
  when: db.changed

- name: Create first user!
  shell: php createAdminUser.php
  args:
    chdir: "{{ onboard_path }}/scripts"
  when: db.changed

- name: Delete createAdminUser script
  file:
    path: "{{ onboard_path }}/scripts/createAdminUser.php"
    state: absent
