---
- name: Clone the repository
  become: no
  git:
    repo: https://github.com/City-of-Bloomington/onboard.git
    dest: "{{ onboard_path }}"
    update: yes
  notify: onboard update permissions

- name: Install Core Dependencies
  become: no
  composer:
    command: update
    working_dir: "{{ onboard_path }}"

- name: Install Theme Dependencies
  become: no
  composer:
    command: update
    working_dir: "{{ onboard_path }}/data/Themes/Kirkwood"

- name: Install Factory Number One Dependencies
  become: no
  npm:
    path: "{{ onboard_path }}/data/Themes/Kirkwood/vendor/City-of-Bloomington/factory-number-one"
    global: no

- name: Build the application
  become: no
  command: "{{ onboard_path }}/build.sh"
  args:
    chdir: "{{ onboard_path }}"

- name: Configure application instance
  template: src=site_config.inc dest={{ onboard_path }}/data/
  notify: onboard update permissions

- name: Configure Theme
  template: src=theme_config.inc dest={{ onboard_path }}/data/Themes/Kirkwood
  notify: onboard update permissions

- name: Install credentials file
  copy:
    content: "{{ onboard_google.credentials }}"
    dest: /etc/ssl/private/{{ apache_ssl.key.file }}
    mode: 0640
  when: apache_ssl.key.data is defined
  no_log: True
