galaxy_info:
  description: Role for maintaining OnBoard on Ubuntu
  company: City of Bloomington, Indiana
  issue_tracker_url: https://github.com/City-of-Bloomington/OnBoard/issues
  license: GPLv3
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - xenial

  galaxy_tags:
    - ubuntu
    - web
    - php

dependencies:
  - { role: City-of-Bloomington.mysql  }
  - { role: City-of-Bloomington.php    }
  - { role: City-of-Bloomington.nodejs }
